repos:
  - repo: local
    hooks:
      # Format code uniformly
      - id: ruff-format
        name: Formatter (Ruff)
        language: system
        entry: ruff format
        types: [ python ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Trim trailing whitespace
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude_types: [ python ] # No use checking Python as Ruff has already done it
      # Ensure files end with an empty line
      - id: end-of-file-fixer
        name: Ensure files end in a single blank line
        exclude_types: [ python ] # No use checking Python as Ruff has already done it
  - repo: local
    hooks:
      # Flag (and fix, if possible) lint errors
      - id: ruff
        name: Linter (Ruff)
        language: system
        entry: ruff check
        types: [ python ]
      # Static type checking
      - id: mypy
        name: Static type checker (mypy)
        language: system
        entry: mypy
        types: [ python ]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
      - id: poetry-check
        name: Check Poetry configuration
      - id: poetry-lock
        name: Ensure Poetry lockfile is up-to-date
