repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        language: system
        entry: ruff check
        types: [python]

      - id: ruff-format
        name: ruff format
        language: system
        entry: ruff format
        types: [python]

