name: CI (code style and tests)

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # This is required for the Poetry lockfile check to pass (as it checks the Python version and the default is 3.10)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    strategy:
      matrix:
        python: ["3.11", "3.12"]
    runs-on: ubuntu-latest
    name: Tests (Python ${{ matrix.python }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # These steps taken entirely from Manim's CI workflow, https://github.com/ManimCommunity/manim/blob/main/.github/workflows/ci.yml
      - name: Install dependencies (system)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3-opengl libpango1.0-dev xvfb freeglut3-dev
          version: 1.0
      - name: Install dependencies (LaTeX)
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            scheme-basic latex fontspec tipa calligra xcolor
            standalone preview doublestroke setspace rsfs relsize
            ragged2e fundus-calligra microtype wasysym physics dvisvgm jknapltx
            wasy cm-super babel-english gnu-freefont mathastext cbfonts-fd xetex
      - name: Start virtual display (xvfb)
        run: sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Install dependencies (uv)
        run: uv sync --all-extras --locked

      - name: Run tests
        run: uv run python -m pytest
